apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: poultondergsspringbootdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poultondergsspringbootdocker 
    spec:
      containers:
        - name: poultondergsspringbootdocker 
          image: mycontainerregistrypot.azurecr.io/poultondergsspringbootdocker
          ports:
          - containerPort: 80